project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as Marketplace



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls') ),
    path('marketplace/', include('marketplace.urls') ),
    path('search/', Marketplace.search, name="search"  ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/forms.py
from django import forms
from .models import *

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput()) # bu sekilde confirm password olayini da ekliyoruz

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

    
    def clean(self): #raise error if passwords doesnt match
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}))
    cover_photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'btn btn-info'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your address here', 'required':'required'}))
    latitude = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    longitude = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:

        model = UserProfile
        fields = ['profile_picture', 'cover_photo', 'address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude']

project/templates/add_category.html
{% extends "base.html" %}

{% load static %}
{% block content %}

{% include 'alerts.html' %}
<!-- Main Section Start -->
<div class="main-section">
   {% include "cover.html" %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="user-account-nav user-account-sidebar">
                        {% include "v_sidebar.html" %}
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <h2>Build your food menu</h2>
                            <hr>
                                <h5>Add new Category</h5>
                          
                                <form action="{% url 'add_category'%}" method="POST" >

                                    {{form}}


                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->



{% endblock %}

project/templates/c_sidebar.html
<div class="user-nav-list">
    <ul>
        <li class="active"><a href="restaurant-dashboard.html"><i class="icon-dashboard3"></i>Dashboard</a></li>
        <li><a href="restaurant-restaurant.html"><i class="icon-building"></i>My Orders</a></li>
        <li><a href="restaurant-menu-builder.html"><i class="icon-menu5"></i>Profile settings</a></li>
        <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
    </ul>
</div>

project/templates/cover.html
{% load static %}


<div class="page-section restaurant-detail-image-section" style=" background: url({{vendor.user_profile.cover_photo.url}}) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <!-- Column Start -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="company-info-detail">
                    <div class="company-info">
                        <div class="img-holder">
                            <figure>
                                <img src="{{vendor.user_profile.profile_picture.url}}" alt="">
                            </figure>
                        </div>

                        <div class="text-holder">
                            <span class="restaurant-title">{{vendor.vendor_name}}</span>
                            <div class="text">
                                <i class="icon-location"></i>
                                <p>{{vendor.user_profile.address}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>

project/templates/edit_category.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<!-- Main Section Start -->
<div class="main-section">
   {% include "cover.html" %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="user-account-nav user-account-sidebar">
                        {% include "v_sidebar.html" %}
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <h2>Build your food menu</h2>
                            <hr>
                                <h5>Edit Category</h5>
                          
                                <form action="{% url 'edit_category' category.id%}" method="POST" >
                                    {% csrf_token %}
                                    <div class="form-fields-set">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12">
                                                <div class="field-holder">
                                                    <label>Category Name</label>
                                                    {{form.category_name}}
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <div class="field-holder">
                                                    <label>Description</label>
                                                    {{form.description}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors  %}
                                                <li style="color: red;">{{error}}</li>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}

                                    <button type="submit" class="btn btn-info">Update</button>
                                    {% include 'alerts.html' %}

                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->



{% endblock %}

project/templates/fooditems_by_category.html
{% extends "base.html" %}

{% load static %}
{% block content %}

{% include 'alerts.html' %}
<!-- Main Section Start -->
<div class="main-section">
   {% include "cover.html" %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="user-account-nav user-account-sidebar">
                        {% include "v_sidebar.html" %}
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <h2>Build your food menu</h2>
                            <hr>
                                <h5>Category: <span class="text-success">{{category}}</span></h5>


                                {% if fooditems %} <!--if there is food items-->
                                <table class="table">
                                    <tbody>
                                    {% for i in fooditems %}
                                        
                                    <tr>
                                        <th>{{forloop.counter}}</th>
                                        <td> <img src="{{i.image.url}}" width="40" alt=""></td>
                                        <td>
                                            <a href=""><p class="mb-0"><b>{{i.food_title}}</b></p></a>
                                            <small class="text-muted">{{i.description}}</small>
                                        </td>
                                        <td><a href="{% url 'edit_food' i.id %}"><i class="fa fa-pencil" style="margin-right: 20px;"></i></a>
                                          <a href="{% url 'delete_food' i.id %}" onclick="return confirm('Are you sure you want to delete {{i.food_title}}' )"><i class="fa fa-trash text-danger"></i></a>
                                        </td>
                                    </tr>

                                    {% endfor %}
        
                                    </tbody>
                                </table>
                                
                                {%else%}
                                <div class="mt-5">
                                    <h5 class="text-center">No food items found</h5>
                                    <div class="text-center">
                                        <a href="" class="btn btn-success"><i class="fa fa-plus"></i> Add Food</a>
                                    </div>
                                </div>
                                {%endif%}
                                
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->



{% endblock %}

project/templates/home.html
{% extends "base.html" %}

{% load static %}
{% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url(assets/extra-images/bg-image1.jpg) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form action="{% url 'search' %}" method="GET" >
									<div class="row">
										<div class="col-lg-4 col-md-6 col-sm-5 col-xs-12">
											<div class="field-holder">
												<input name="keyword" type="text" placeholder="Resturant or food name" style=" text-transform: lowercase;" >
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															<span id="foodbakery_radius_location_open333" class="foodbakery-radius-location"><i class="icon-target5"></i></span>

															<input type="text" name="address" class="location-field-text filter" id="id_address" required placeholder="All Locations">
															<input type="hidden" name="lat" value="" id="id_latitude">
															<input type="hidden" name="lng" value="" id="id_longitude">
														</div>
												
													</li>
												</ul>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<select name="radius" id="radius" style="height: 50px;">
												<option value="" selected>Choose Radius</option>
												<option value="5">5Km</option>
												<option value="10">10Km</option>
												<option value="15">15Km</option>
												<option value="20">20Km</option>
												<option value="50">50Km</option>
												<option value="100">100Km</option>
											</select>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Search">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			<!-- Main Search End -->
			
			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="company-logo">
								<ul>
									{% for i in  vendors %}
									<li class="has-border">
										<figure>
											<a href="#"><img src="{{i.user_profile.profile_picture.url}}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for i in  vendors %}


									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure><a href="#"><img src="{{i.user_profile.profile_picture.url}}" class="img-thumb wp-post-image" alt=""></a></figure>
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Close
												</span>
											</div>
											<div class="text-holder">
												<div class="list-rating">
													<div class="rating-star">
														<span class="rating-box" style="width: 100%;"></span>
													</div>
													<span class="reviews">(1)</span>
												</div>
												<div class="post-title">
													<h5>
														<a href="listing-detail.html">{{i.vendor_name}}</a>
													</h5>
												</div>
												<address>{{i.user_profile.address}}</address>
											</div>
											
										</div>
									</li>
									
									
									{% endfor %}
									
									
				
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->
		</div>
		<!-- Main Section End -->
{% endblock %}

project/templates/login.html
{% extends "base.html" %}

{% load static %}
{% block content %}
		<!-- Main Section Start -->
		<div class="main-section">
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 60px;margin-bottom: 0px;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="user-dashboard loader-holder" style="width: 500px; min-height:auto ;">
								<div class="user-holder">
                            <h4 class="text-center" style="margin-bottom: 0;">Log in</h4>
                            <p class="text-center">Order from your favorite restaurants</p>
                            <hr>
                            <div id="restaurant-sets-holder">
                                <form class="form-fields-set foodbakery-dev-restaurant-form" method="post" action="{% url 'login' %}" enctype="multipart/form-data">
									{% csrf_token %}
                                    <ul class="register-add-restaurant-tab-container restaurant-informati\on-tab-container">
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="row">

																<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
																	<div class="field-holder">
																		<label>Email address</label>
                                                                        <input type="email" name="email" placeholder="Enter your email">
																	</div>
																</div>
														
															
														
																<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
																	<div class="field-holder">
																		<label>Password</label>
                                                                        <input type="password" name="password" placeholder="Enter your password">
																	</div>
																</div>

                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <div class="payment-holder">
                                                            <input type="submit" value="Submit" id="btn-next-restaurant-information" class="bgcolor">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
											<div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
													{% include "alerts.html" %}
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Main Section End -->
	</div>
	<!-- Modal Popup Start -->
	<div class="modal fade" id="sign-in" aria-labelledby="myModalLabel">
		<div class="modal-dialog">
			<div class="login-form">
				<div class="modal-content">
					<div class="tab-content">
						<div id="user-login-tab" class="tab-pane fade in active">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">×</span>
								</button>
								<h5 class="modal-title foodbakery-dev-login-main-title">Login To Your Account</h5>
							</div>
							<div class="modal-body">
								<p class="foodbakery-dev-login-top-msg"></p>
								<div class="cs-login-pbox">
									<div class="status status-message"></div>
									<form class="wp-user-form webkit">
										<div class="cs-demo-login">
											<div class="cs-demo-login-lable text-color">Click to login with Demo User
											</div>
											<div class="clearfix"></div>
											<ul class="login-switches">
												<li>
													<a href="restaurant-dashboard.html" class="btn-red demo-publisher-user"><i class="icon-food"></i> Restaurant</a>
												</li>
												<li>
													<a href="buyer-dashboard.html" class="btn-red btn-green demo-buyer-user"><i class="icon-user4"></i> Buyer</a>
												</li>
											</ul>
										</div>
										<div class="input-filed">
											<i class="icon-user4"></i>
											<input type="text" placeholder="Username">
										</div>
										<div class="input-filed">
											<i class="icon-unlock-alt"></i>
											<input type="password" value="Password">
										</div>
										<div class="forget-password">
											<a data-toggle="tab" href="#user-password" class="cs-forgot-switch forgot-switch">Forgot Password?</a>
										</div>
										<div class="input-filed input-field-btn">
											<div class="ajax-login-button input-button-loader">
												<input type="button" class="cs-bgcolor" value="Log in">
											</div>
										</div>
									</form>
									<div class="signin-tab-link forget-password">
										New Here?
										<a data-toggle="tab" href="#user-register" class="foodbakery-dev-login-box-btn forgot-switch">Signup</a>
									</div>
									<div class="footer-element comment-form-social-connect social_login_ui ">
										<div class="social-media">
											<h6><span>Login with</span></h6>
											<ul>
												<li><a href="#" title="Facebook" data-original-title="Facebook" class="social_login_login_facebook facebook"><span class="social-mess-top fb-social-login" style="display:none">Please set API key</span><i class="icon-facebook"></i>Sign In With Facebook</a></li>
												<li><a href="#" title="Twitter" data-original-title="twitter" class="social_login_login_twitter twitter"><span class="social-mess-top tw-social-login" style="display:none">Please set API key</span><i class="icon-twitter3"></i>Sign In With Twitter</a></li>
												<li><a href="#" rel="nofollow" title="google-plus" data-original-title="google+" class="social_login_login_google gplus"><span class="social-mess-top gplus-social-login" style="display:none">Please set API key</span><i class="icon-google4"></i>Sign In With Google</a></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div id="user-register" class="tab-pane fade">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">×</span> </button>
								<h5 id="myModalLabel" class="modal-title">Sign Up</h5>
							</div>
							<div class="modal-body">
								<div role="tabpanel" class="tab-pane active">
									<div id="result_296069" class="status-message"></div>
									<form class="wp-user-form demo_test">
										<div class="input-filed foodbakery-company-name">
											<i class="icon-v-card"></i>
											<input type="text" placeholder="Company Name">
										</div>
										<div class="input-filed">
											<i class="icon-user4"></i>
											<input type="text" placeholder="Username">
										</div>
										<div class="input-filed">
											<i class="icon-v-card"></i>
											<input type="text" placeholder="Display Name">
										</div>
										<div class="input-filed">
											<i class="icon-email"></i>
											<input type="email" placeholder="Email">
										</div>
										<span class="signup-alert">
											<b>Note :</b> Please enter your correct email and we will send you a
											password
											on that email.
										</span>
										<div class="checkbox-area">
											<input type="checkbox" id="terms-head" class="foodbakery-dev-req-field">
											<label for="terms-head">
												By Registering You Confirm That You Accept theme
												<a target="_blank" href="#">
													Terms &amp; conditions
												</a>
												And
												<a target="_blank" href="#">
													Privacy Policy
												</a>
											</label>
										</div>
										<div class="side-by-side select-icon clearfix">
											<div class="select-holder"></div>
										</div> 
										<div class="checks-holder">
											<div class="input-filed input-field-btn">
												<div class="ajax-signup-button input-button-loader">
													<input type="button" value="Sign Up">
												</div>
											</div>
										</div>
									</form>
									<div class="register_content"></div>
									<div class="create- signin-tab-link ">Already have an account?
										<a data-toggle="tab" href="#user-login-tab" class="foodbakery-dev-signup-box-btn">Login here</a>
									</div>
									<div class="footer-element comment-form-social-connect social_login_ui">
										<div class="social-media">
											<h6><span>Login with</span></h6>
											<ul>
												<li><a href="javascript:void(0);" title="Facebook" data-original-title="Facebook" class="social_login_login_facebook facebook"><span class="social-mess-top fb-social-login" style="display:none">Please set API key</span><i class="icon-facebook"></i>Sign In With
														Facebook</a></li>
												<li><a href="javascript:void(0);" title="Twitter" data-original-title="twitter" class="social_login_login_twitter twitter"><span class="social-mess-top tw-social-login" style="display:none">Please set API key</span><i class="icon-twitter3"></i>Sign In With
														Twitter</a></li>
												<li><a href="javascript:void(0);" rel="nofollow" title="google-plus" data-original-title="google+" class="social_login_login_google gplus"><span class="social-mess-top gplus-social-login" style="display:none">Please set API key</span><i class="icon-google4"></i>Sign In With
														Google</a></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div id="user-password" class="tab-pane fade">
							<div class="content-style-form cs-forgot-pbox content-style-form-2">
								<div>
									<form class="user_form">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">×</span>
											</button>
											<h5 class="modal-title foodbakery-dev-login-main-title">Create Your Food
												Bakery Account</h5>
										</div>
										<div class="modal-body modal-body-loader">
											<span class="alert-info">Enter your email address below and we'll send you
												an
												email with instructions on how to change your password</span>
											<div class="input-filed">
												<i class="icon-email"></i>
												<input type="text" placeholder="Enter email address..." name="user_input">
											</div>
											<div class="input-filed input-field-btn">
												<div class="ajax-forgot-button input-button-loader">
													<input type="submit" class="reset_password cs-bgcolor" name="submit" value="Submit">
												</div>
											</div>
											<div class="forget-password">
												<a data-toggle="tab" href="#user-login-tab" class="cs-login-switch forgot-switch triggered-click">Login Here</a>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endblock %}

project/templates/menu-builder.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<!-- Main Section Start -->
<div class="main-section">
   {% include "cover.html" %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <div class="user-account-nav user-account-sidebar">
                        {% include "v_sidebar.html" %}
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <h2>Build your food menu</h2>
                            <hr>
                            <table class="table">
                                <h5>Menu Categories</h5>
                                <a href="{% url 'add_food' %}" class="btn btn-success float-right m-1" >Add Food</a>
                                <a href="{% url 'add_category' %}" class="btn btn-info float-right m-1" >Add Category</a>
                                <tbody>
                                {% for i in categories %}
                                    
                                  <tr>
                                    <th>{{forloop.counter}}</th>
                                    <td>
                                        <a href="{% url 'fooditems_by_category' i.id %}"><p class="mb-0"><b>{{i.category_name}}</b></p></a>
                                        <small class="text-muted">{{i.description}}</small>
                                    </td>
                                    <td>
                                        <a href="{% url 'edit_category' i.id %}"><i class="fa fa-pencil" style="margin-right: 20px;"></i></a>
                                        <a href="{% url 'delete_category' i.id %}" onclick="return confirm('Are you sure you want to delete {{i.category_name}}?')" ><i class="fa fa-trash text-danger"></i></a>
                                    </td>
                                  </tr>

                                {% endfor %}
    
                                </tbody>
                              </table>
                                        {% include 'alerts.html' %}
                       
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->



{% endblock %}